

version: '3.9'

services:
  db:
    image: postgres:16 # Используйте нужную версию PostgreSQL
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: egor # Имя пользователя БД
      POSTGRES_PASSWORD: 12345 # Пароль пользователя
      POSTGRES_DB: my_database # Название базы данных
      PGDATA: /var/lib/postgresql/data/pgdata # Кастомный путь хранения данных
    volumes:
      - db_data:/var/lib/postgresql/data # Маппинг локальной директории для хранения данных
    ports:
      - "5432:5432" # Отображение порта контейнера на хост-машину
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U egor -d my_database"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - db_network

volumes:
  db_data: {} # Определение тома для хранения данных

networks:
  db_network:
    driver: bridge
